### ISSUE TITLE
 AliCloud credentials missing

### ISSUE THREAD

**Issue by iTanken** [tuotoo/qiniu-auto-cert#1]
你好，我用的是 alicloud DNS，AK 和 SK 都配置了，请问一下为什么会提示 ` AliCloud credentials missing`？
环境变量：
![image](https://user-images.githubusercontent.com/23544702/56332969-ef6ea180-61c4-11e9-828d-0663f5a195cd.png)
```bash
set "DNS_PROVIDER=alicloud"
set "ALICLOUD_ACCESS_KEY=***"
set "ALICLOUD_SECRET_KEY=***"
```

Window 下运行提示:
```bash
[INFO] acme: Trying to resolve account by key
obtain and upload cert failed: AliCloud credentials missing
```

**Comment by jqs7** [comment]
使用的是 v0.1.0 release 么？
因为之前 lego 没有支持阿里云，所以是把一个阿里云的 PR 合并到 vendor 里边进行编译的。
在那里边使用的环境变量是 `ALICLOUD_API_KEY` 和 `ALICLOUD_API_SECRET`

**Comment by iTanken** [comment]
谢谢，是 0.1.0，改了环境变量名之后阿里云没问题了，但是又有新的问题：
```
2019/04/19 08:46:54 [INFO]  acme: Obtaining SAN certificate
2019/04/19 08:46:55 [INFO]  AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/*******************
2019/04/19 08:46:55 [INFO]  acme: Could not find solver for: tls-alpn-01
2019/04/19 08:46:55 [INFO]  acme: Trying to solve DNS-01
2019/04/19 08:46:56 [INFO]  Checking DNS record propagation using [google-public-dns-a.google.com:53 google-public-dns-b.google.com:53]
```
求新版 release 😀

**Comment by jqs7** [comment]
em...
查看了下 lego 的源码，在 /etc/resolv.conf 中获取 DNS 失败的情况下，默认会使用 google-public-dns-a.google.com:53 和 google-public-dns-b.google.com:53 这两个服务器...

**Comment by iTanken** [comment]
> em...
> 查看了下 lego 的源码，在 /etc/resolv.conf 中获取 DNS 失败的情况下，默认会使用 google-public-dns-a.google.com:53 和 google-public-dns-b.google.com:53 这两个服务器...

哦哦，好的，也就是说不能用 Windows 系统是吧？😂

**Comment by jqs7** [comment]
> > em...
> > 查看了下 lego 的源码，在 /etc/resolv.conf 中获取 DNS 失败的情况下，默认会使用 google-public-dns-a.google.com:53 和 google-public-dns-b.google.com:53 这两个服务器...
> 
> 哦哦，好的，也就是说不能用 Windows 系统是吧？😂

我尝试下往里边添加额外的 DNS 服务器地址来解决这个问题

**Comment by jqs7** [comment]
> > em...
> > 查看了下 lego 的源码，在 /etc/resolv.conf 中获取 DNS 失败的情况下，默认会使用 google-public-dns-a.google.com:53 和 google-public-dns-b.google.com:53 这两个服务器...
> 
> 哦哦，好的，也就是说不能用 Windows 系统是吧？😂

我尝试下往里边添加额外的 DNS 服务器地址来解决这个问题

**Comment by iTanken** [comment]
为什么回复了两次 😂

**Comment by jqs7** [comment]
网络原因...扶额

**Comment by jqs7** [comment]
@iTanken 尝试修复了下，现在默认使用 223.5.5.5 与 1.1.1.1 
使用 v0.1.1 试试看

**Comment by iTanken** [comment]
> @iTanken 尝试修复了下，现在默认使用 223.5.5.5 与 1.1.1.1
> 使用 v0.1.1 试试看

好的，感谢。我试一下

**Comment by iTanken** [comment]
可以了的，成功更新了证书 👍，但是会提示证书删除失败，这应该没有影响吧？
```
 acme: Trying to solve DNS-01
 Checking DNS record propagation using [223.5.5.5:53 1.1.1.1:53]
 The server validated our request
 acme: Validations succeeded; requesting certificates
 Server responded with a certificate.
 delete cert failed: 400611: 证书已绑定域名
```

**Comment by jqs7** [comment]
🎉  没有影响的

**Comment by iTanken** [comment]
> 🎉 没有影响的

好的 👌
